### ISSUE TITLE
Update CHANGELOG to include 3.0 changes, and add pending changes for 4.0

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-inflector#155]

**Comment by richard-viney** [comment]
Related to this, the String prototype extensions in this add-on were deprecated and expected to be removed in 3.0.0, but are actually still present. There's since been a branch merged to get rid of them, could this be released as 3.0.2?

Upgrading from Ember 3.12 to 3.14 I've started seeing the above deprecation warnings being thrown even though no code is actually using the methods. This is due to something in Sinon that is copying prototype definitions, resulting in String.pluralize being retrieved, triggering the deprecation, but never actually being called.

**Comment by sandstrom** [comment]
We have this issue too.

Great if the "remove in 3.0.0" stuff could be removed and re-released as 3.0.2.
